apiVersion: v1
kind: Pod
metadata:
  name: gp1-baolin
spec:
  containers:
  - name: mypod
    image: nvidia/cuda:11.7.1-runtime-ubuntu20.04
    resources:
      limits:
        memory: 1Gi
        cpu: 1
        nvidia.com/gpu: 1
      requests:
        memory: 500Mi
        cpu: 100m
        nvidia.com/gpu: 1
    command: ["sh", "-c", "sleep 1000"]
