apiVersion: v1
kind: Pod
metadata:
  name: gp2-baolin
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-GTX-1070
            - NVIDIA-GeForce-GTX-1080-Ti
  containers:
  - name: mypod
    image: nvidia/cuda:11.7.1-runtime-ubuntu20.04
    resources:
      limits:
        memory: 1.5Gi
        cpu: 1
        nvidia.com/gpu: 1
      requests:
        memory: 500Mi
        cpu: 100m
        nvidia.com/gpu: 1
    command: ["sh", "-c", "sleep 1000"]
