apiVersion: v1
kind: Pod
metadata:
  name: gp3-baolin
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
            - Tesla-T4
  containers:
  - name: mypod
    image: nvidia/cuda:11.7.1-runtime-ubuntu20.04
    resources:
      limits:
        memory: 1.5Gi
        cpu: 1
        nvidia.com/gpu: 1
      requests:
        memory: 500Mi
        cpu: 100m
        nvidia.com/gpu: 1
    command: ["sh", "-c", "sleep 1000"]
